version: "3.8"

services:
  meebotv2:
    container_name: meebotv2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10008:10008"
    networks:
      - webnet
    env_file: .env

networks:
  webnet:

