version: "3.8"

services:
  meebot:
    container_name: meebot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    networks:
      - webnet
    env_file: .env

networks:
  webnet:

