services:
  - type: web
    name: mee06/bot
    runtime: node
    plan: starter
    buildCommand: cd servers/bot && bun install && bun run build
    startCommand: cd servers/bot && node dist/index.js
    buildFilter:
      paths:
        - servers/bot/**/*.ts
        - servers/bot/*.json
    envVars:
      - fromGroup: mee06/servers/bot